name: Scrape and Update MongoDB

on:
  schedule:
    - cron: "0 8 * * *"   # every day at 8 AM UTC
  workflow_dispatch:       # allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt
          playwright install --with-deps chromium

      - name: Run scraper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          python scraper.py
