name: Update Data JSON

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch: # allow manual trigger too


jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
            contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt
          playwright install --with-deps chromium

      - name: Run scraper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }} # if you still use MongoDB
        run: |
          python scraper/scraper.py

      - name: Commit and push data.json
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

            if git diff --quiet site/data.json; then
            echo "No changes in data.json"
            else
            git add site/data.json
            git commit -m "Update data.json from scraper"
            git push
            fi