name: Update Data JSON

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch: # allow manual trigger too

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Run scraper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }} # if you still use MongoDB
        run: |
          python scraper.py

      - name: Commit updated data.json
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add site/data.json
          git commit -m "Update data.json [skip ci]" || echo "No changes to commit"
          git push